= Governance App Template

The Governance App Template is a customizable, extensible host UI designed to simplify the creation and management of applications build atop Aragon OSx. It uses modular pages that represent different aspects of your DAO’s governance to help you rapidly create and adapt your UI to the unique needs of your organization.

== Getting Started

Use the template as-is or customize it with your own plugins and integrations.

In the following pages, you’ll learn how to set up the development environment, check out some example modules, integrate secure encryption flows add plugins, and add your own plugin:

- xref:installation.adoc[Installation]
- xref:example-modules.adoc[Example Modules]
- xref:encrypted-proposal.adoc[Encrypted Proposals]
- xref:adding-your-own-plugin.adoc[Adding Your Own Plugin]

== Contributions

Got ideas on how to make this template even better? We welcome bug fixes, feature proposals, and new plugins. 

If you want to stay in sync with upstream changes, configure your repository as follows:

```bash
bash
Copy code
git remote add upstream git@github.com:aragon/gov-app-template.git
git remote set-url --push upstream DISABLE
```

== Need Help?

Join our link:https://discord.gg/aragonorg[Discord channel] for support, advice, or to share your work with other community members.

== License

The Governance App Template is released under the **AGPL v3 License**. Refer to the `LICENSE` file for more details.
